### ISSUE TITLE
R2: Prototype updates to Figaro faceted search UI to support showing the ETC table

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/maap-hec-aws#12]
Integrate the model Flask app into Figaro.  From Figaro, make calls to the Flask app to get estimated time to completion (ETC).  Parse the response and present it as a table in the Figaro UI.
DoD:
- [ ] Documentation in Flask app repo 
- [ ] HySDS UI updates pushed to the MAAP org
- [ ] Demo: Figaro faceted user interface shows ETC table.

**Comment by jjacob7734** [comment]
Initial implementation completed, but needs more testing before deployment to target environment (TBD).
