### ISSUE TITLE
Get onboarded to Pleiades

### ISSUE THREAD

**Issue by jjacob7734** [MAAP-Project/maap-hec-aws#48]
1. Fill out NAS/Pleaides user request form
1. Give Bob Ciotti a heads up that a new user is added
1. Once Pleaides account is open, NAS can give access to AWS/SQS (temporary access until MCP is available).

**Comment by mkarim2017** [comment]
I have completed the Onboarding.
I can log in to NAS/Pleaides.
Also can create SQS queues using temporary access key.
