### ISSUE TITLE
Add "node_type" to ADES-K8S metrics schema

### ISSUE THREAD

**Issue by jjacob-jpl** [MAAP-Project/maap-hec-aws#59]
The ADES-K8S metrics collection needs to include the node/instance type for each step of the workflow (stage-in, process, stage-out). Name this new keyword "node_type".

Definition of Done:

- [ ] Metrics collection includes "node_type" keyword for each workflow step.
- [ ] The node_type is in the getStatus metrics JSON
- [ ]  @mkarim2017 metrics aggregation works with new schema

**Comment by jjacob7734** [comment]
Replaced by other ticket.
