### ISSUE TITLE
R2: Reference implementation of 3-step jobs

### ISSUE THREAD

**Issue by jjacob-jpl** [MAAP-Project/maap-hec-aws#61]
Improved reference implementation that incorporates the data access mechanisms from MSFC.  Work with MSFC to determine the API to use for data access.

**Comment by jjacob7734** [comment]
Final reference implementation of downsample-dem is at https://github.com/pymonger/downsample-dem.  This has been tested via WPS-T endpoints on ADES-PBS and ADES-K8s.
