### ISSUE TITLE
Determine what is MAAP's API for data access 

### ISSUE THREAD

**Issue by jjacob-jpl** [MAAP-Project/maap-hec-aws#62]
Meet with MSFC team to determine:

- Data access API documentation
- Credentials
- Example STAC documents

Definition of Done:
- [ ] Documentation on data access API, credentials needed
- [ ] Example STAC documents for data access

**Comment by pymonger** [comment]
Met with @bsatoriu and he showed us how to use the MAAP API and client library as well as provided credentials/tokens needed.
