### ISSUE TITLE
Provide the S3 buckets to JPL Dev Team for stage-out

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-hec-aws#65]
## Description
The Pleiades (PBS) processing job's output written to a designated 'output' folder should be uploaded to the AWS MAAP (HEC) buckets to make it available on MAAP's Algorithm Development Environment (ADE). For PBS to upload output data to AWS MAAP (HEC), create the necessary S3 buckets and ensure that they have the correct bucket policies applied. 

### Acceptance Criteria:

- [x] S3 buckets for Pleiades (PBS) job output are created
- [x] AWS S3 output buckets have the correct permissions for JPL's stage-out process output upload
- [x] Documentation provided
- [x] Github repo commits provided

**Comment by wildintellect** [comment]
Questions for JPL team:
1. Should outputs for each user go to a designated `hec_output` folder (sub key)?
2. Will HEC need long term credentials or should HEC processes assume a role to get temporary permissions to write data?

**Comment by wildintellect** [comment]
Bucket and policies should be deployed by Terraform to be in line with JPL methods for deployment.

**Comment by jjfrench** [comment]
There was some discussion regarding adding additional Github repositories for the terraform deployment of the buckets and their policies, did we get anywhere with that?

**Comment by wildintellect** [comment]
We agreed to create a private repo in the maap-project org. No name was set, nor was the repo started. You can start if you want @jjfrench

**Comment by wildintellect** [comment]
Access from MCP HEC account to MAAP OPS Workspace bucket is confirmed s3://maap-ops-workspace/
```
[cloudshell-user@ip-10-0-159-139 ~]$ aws s3 ls s3://maap-ops-workspace/
                           PRE /
                           PRE abarenblitt/
                           PRE admin/
                           PRE aimeeb/
                           PRE alanxuliang/
                           PRE alexdevseed/
```
Also tested copying a file.
