### ISSUE TITLE
R1: Write quickstart guide for end user to create application package through CI/CD.

### ISSUE THREAD

**Issue by jjacob7734** [MAAP-Project/maap-hec-aws#8]
DoD:
- [X] documentation at https://repo.dit.maap-project.org/max.zhan/app-pack-generator/-/blob/main/README.md
- [X] gitlab repo location at https://repo.dit.maap-project.org/max.zhan/app-pack-generator/-/tree/main
- [ ] live demo
- [ ] verification/validation of user guide by tester (developer other than assignee)

**Comment by jplzhan** [comment]
Documentation for the application package builder is provided through https://repo.dit.maap-project.org/max.zhan/app-pack-generator/-/blob/main/README.md.

Some pipeline testing has been independently done by Alex Goodman and Joseph Jacob.

End-to-end testing for running the package on Pleiades is still required.
