### ISSUE TITLE
Data Manifest Capability (In)

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/maap-hec-aws#85]
## Description
For jobs, the data required ideally should be clearly specified upfront. This is equivalent to the existing DPS input yaml `Download=True`.
HEC jobs will need a similar way to supply urls (https or s3), likely in CWL format to the stage-in executor.

Long term, future iterations (another ticket) may modify this to be a json in STAC format that is translated or iterated by the CWL stage-in. This is not part of this ticket.

## Acceptance Criteria
- [ ] Stage In Recipe with data specified
- [ ] Documentation provided
- [ ] Github repo commits provided
- [ ] Live demo provided

**Comment by wildintellect** [comment]
In discussions with @jplzhan and @jjacob7734 this is going to be an array of values passed to the submitJob. @jjacob7734 please confirm the name of the variable you want to use.

Example
```
file_inputs: ["s3://URI1", "https://URI2"]
```

**Comment by jjacob7734** [comment]
I think the name of the variable can be anything.  In the CI/CD @jplzhan will mark that input variable as a stage_in variable in the application descriptor JSON file.  The ADES will use that marking to identify the stage in variable, whatever it is named.

Max, can you confirm that the science users building the application can use any keyword they like in the manifest?

**Comment by moronidav** [comment]
@jplzhan confirmed today that whis was resolved in verified. @wildintellect Feel free to close this out.
