### ISSUE TITLE
R2: provide baseline stage-out capability (not dependent on caching)

### ISSUE THREAD

**Issue by pymonger** [MAAP-Project/maap-hec-aws#89]
The stage-out capability shall be a single-point executable/script that has capability to support the following use cases:

- stage out data to an S3 URL (allowing authentication via AWS access/secret keys or unsigned requests)

Definition of Done:
- [] stage_out.py script that handles the above use cases
- [] CWL documents that demonstrate the above use cases
- [] Documentation provided
- [] Github repo commits provided
- [x] Live demo provided

**Comment by jjacob7734** [comment]
Used as a baseline for the CI/CD implementation.  The stage out is to the MAAP-HEC bucket.
